from __future__ import annotations

from typing import Any

DEFAULT_SEO = {
    "title": "SiteForge AI — Generated Website",
    "description": "A modern website generated by SiteForge AI.",
    "keywords": ["website", "modern", "professional"],
    "og_title": "SiteForge AI — Generated Website",
    "og_description": "A modern website generated by SiteForge AI.",
}

DEFAULT_NAVBAR = {
    "logo": "https://placehold.co/120x40?text=Logo",
    "links": ["Home", "About", "Contact"],
}

DEFAULT_HERO = {
    "title": "Welcome",
    "subtitle": "Built with SiteForge AI",
    "cta": "Get Started",
}

DEFAULT_FEATURES = [
    {"title": "Fast", "description": "Optimized for performance", "icon": "⚡"},
    {"title": "Secure", "description": "Built with security in mind", "icon": "🔒"},
]

DEFAULT_FOOTER = {
    "text": "© 2026 SiteForge. All rights reserved.",
    "social": [],
}


def enhance_template(data: dict[str, Any]) -> dict[str, Any]:
    """Return a new dict with fallback values for any missing or empty sections."""
    if not isinstance(data, dict):
        raise TypeError(f"Expected dict, got {type(data).__name__}")

    result = data.copy()

    result.setdefault("seo", DEFAULT_SEO)
    result.setdefault("navbar", DEFAULT_NAVBAR)
    result.setdefault("hero", DEFAULT_HERO)
    result.setdefault("features", DEFAULT_FEATURES)
    result.setdefault("footer", DEFAULT_FOOTER)

    if isinstance(result.get("seo"), dict):
        result["seo"] = {**DEFAULT_SEO, **result["seo"]}

    if isinstance(result.get("navbar"), dict):
        result["navbar"] = {**DEFAULT_NAVBAR, **result["navbar"]}

    if isinstance(result.get("hero"), dict):
        result["hero"] = {**DEFAULT_HERO, **result["hero"]}

    if isinstance(result.get("footer"), dict):
        result["footer"] = {**DEFAULT_FOOTER, **result["footer"]}

    if not result.get("features"):
        result["features"] = DEFAULT_FEATURES

    return result